Repository SparkPost/developers.sparkpost.com, pull requests merged in 2018-07, with the labels that each got.

#242 Removed note prefix from `<banner>`
  content/api/ab-testing.apib
  content/api/metrics.apib
  content/api/smtp-api.apib
  content/api/subaccounts.apib
  content/api/substitutions-reference.apib
  content/api/transmissions.apib
Labels: 📚 documentation

#252 Capitalize banner component
  CONTRIBUTING.md
  content/api/ab-testing.apib
  content/api/inbound-domains.apib
  content/api/ip-pools.apib
  content/api/metrics.apib
  content/api/recipient-lists.apib
  content/api/sending-domains.apib
  content/api/sending-ips.apib
  content/api/smtp-api.apib
  content/api/subaccounts.apib
  content/api/substitutions-reference.apib
  content/api/suppression-list.apib
  content/api/templates.apib
  content/api/transmissions.apib
Labels: 📚 documentation

#253 Removed coming soon Bayesian banner
  content/api/ab-testing.apib
Labels: 📚 documentation

#254 Must provide an empty ip_pool to unassign from a subaccount
  content/api/subaccounts.apib
Labels: 📚 documentation

#251 added Source Code Pro
  package-lock.json
  package.json
  src/components/Layout/index.css.js
  src/components/Layout/index.js
Labels: 🐛 bug

#240 Interactive message events
  content/api/message-events.apib
  content/api/webhooks.apib
  gatsby-config.js
  package.json
  plugins/gatsby-source-sparkpost-api/gatsby-node.js
  plugins/gatsby-source-sparkpost-api/package-lock.json
  plugins/gatsby-source-sparkpost-api/package.json
  plugins/gatsby-transformer-api-blueprint/extend-node-type.js
  plugins/gatsby-transformer-api-blueprint/package-lock.json
  plugins/gatsby-transformer-api-blueprint/package.json
  src/components/api/components/BlockMarkdown/DataStructure.js
  src/components/api/components/BlockMarkdown/EventsTable.js
  src/components/api/components/BlockMarkdown/MessageEvents.js
  src/components/api/components/BlockMarkdown/WebhookEvents.js
  src/components/api/components/BlockMarkdown/index.js
  src/components/api/parts/DataStructure.js
Labels: 📚 documentation, 🔧 enhancement

#259 Puts onus of maintaining version state on .apib files, instead of components
  content/api/ab-testing.apib
  content/api/account.apib
  content/api/inbound-domains.apib
  content/api/ip-pools.apib
  content/api/message-events.apib
  content/api/metrics.apib
  content/api/recipient-lists.apib
  content/api/relay-webhooks.apib
  content/api/sending-domains.apib
  content/api/sending-ips.apib
  content/api/subaccounts.apib
  content/api/suppression-list.apib
  content/api/templates.apib
  content/api/tracking-domains.apib
  content/api/transmissions.apib
  content/api/webhooks.apib
  package-lock.json
  package.json
  src/components/api/parts/Request.js
  src/components/api/parts/Transition.js
Labels: 🔧 enhancement

#260 improved inbound domain descriptions
  content/api/inbound-domains.apib
Labels: 📚 documentation
