Repository SparkPost/developers.sparkpost.com, pull requests merged in 2018-08, with the labels that each got.

#256 EO-35 add docs for deleting tests
  content/api/ab-testing.apib
Labels: 📚 documentation

#241 Updated 404 page
  content/pages/404.js
  src/assets/sparky.svg
Labels: 🔧 enhancement

#274 Mimic React
  content/api/message-events.apib
  content/api/webhooks.apib
  plugins/gatsby-transformer-api-blueprint/data-structures.js
  src/components/api/components/BlockMarkdown/DataStructure.js
  src/components/api/components/BlockMarkdown/MessageEvents.js
  src/components/api/components/BlockMarkdown/WebhookEvents.js
  src/components/api/components/BlockMarkdown/index.js
Labels: 🕰 tech debt

#246 SA-31 Document metrics precision
  content/api/metrics.apib
  package-lock.json
  package.json
Labels: 📚 documentation

#273 Interactive substitutions reference
  .gitignore
  CONTRIBUTING.md
  README.md
  content/api/substitutions-reference.apib
  content/api/table-of-contents.json
  content/api/template-language.apib
  gatsby-config.js
  lambda/substitution-repl.js
  netlify.toml
  package-lock.json
  package.json
  src/components/Markdown/index.js
  src/components/api/DataStructureContext.js
  src/components/api/components/BlockMarkdown/REPL.js
  src/components/api/components/BlockMarkdown/index.js
  static/_redirects
Labels: 📚 documentation, 🔧 enhancement

#280 Remove reference to substitution syntax and substitution engine
  content/api/metrics.apib
  content/api/recipient-lists.apib
  content/api/smtp.apib
  content/api/templates.apib
  content/api/transmissions.apib
Labels: 📚 documentation

#278 Fix Markdown-only navigation
  plugins/gatsby-transformer-api-blueprint/data-structures.js
  plugins/gatsby-transformer-api-blueprint/extend-node-type.js
  plugins/gatsby-transformer-api-blueprint/package-lock.json
  plugins/gatsby-transformer-api-blueprint/package.json
Labels: 🔧 enhancement

#232 Sign Up Button
  src/components/Header/Nav.js
  src/components/Header/Search.js
  src/components/Header/index.js
Labels: 🔧 enhancement

#279 Suppression Sort Param Fix
  content/api/suppression-list.apib
Labels: 📚 documentation

#272 Enterprise inbound fix
  content/api/inbound-domains.apib
Labels: 📚 documentation

#283 optimize images
  src/assets/flame-background.png
  src/assets/libraries/ruby.png
Labels: 🕰 tech debt

#285 favicons
  static/favicons/icon-144x144.png
  static/favicons/icon-192x192.png
  static/favicons/icon-256x256.png
  static/favicons/icon-384x384.png
  static/favicons/icon-48x48.png
  static/favicons/icon-512x512.png
  static/favicons/icon-72x72.png
  static/favicons/icon-96x96.png
Labels: 🐛 bug
